### ISSUE TITLE
[Refactor/Feature?] SharedPreferenceManager Utility

### ISSUE THREAD

**Issue by DarthBenro008** [thunderbiscuit/summerofbitcoin-wallet#1]
I found the code-base to use `sharedPreferences` that is passed to the `Repository`. 

We could implement a `sharedPreferenceManager` Utility, where in one central location we can manage all of our shared preferences which would takes full power of Kotlin and would be much simpler to read!

Advantages of this utility manager:

- One Central location to manage all the shared preferences
- Easier to read, as newbies can intuitively understand what is going on (for people who come from c++, python, java, javaScript)
- Easier Debugging
- Adheres to best practices
- Singleton creation

**Current code-base:** 

https://github.com/thunderbiscuit/summerofbitcoin-wallet/blob/ddb97d37d899a8ca6151fd6c58da963600d53293/app/src/main/java/org/summerofbitcoin/wallet/data/Repository.kt#L32-L36

**Suggested Codebase:**

```kotlin
        sharedPreferencesManager.walletInitialised = true
        sharedPreferencesManager.path = path
        sharedPreferencesManager.descriptor = descriptor
        sharedPreferencesManager.changeDescriptor = changeDescriptor
```

**Comment by thunderbiscuit** [comment]
That's awesome. See PR for small comments!

**Comment by DarthBenro008** [comment]
@thunderbiscuit I cannot see any comments on the PR 😅

**Comment by thunderbiscuit** [comment]
@DarthBenro008 sorry I posted here before putting my comment in the PR thread. Do you see it now? No rush, I just wanted to let you know it was there.

**Comment by DarthBenro008** [comment]
@thunderbiscuit oops, I had not seen the comments, thanks for the ping. I have made the requested changes and pushed :smiley:
